### ISSUE TITLE
Include tests in sdist

### ISSUE THREAD

**Issue by jayvdb** [devsf/pyops#1]
It is helpful for rpm packaging to have the tests in the sdist uploaded to PyPI.

**Comment by d3vsf** [comment]
Hi @jayvdb !
Should I also execute something like

`python setup.py sdist`

as described [here](https://packaging.python.org/glossary/)?

Thanks for your request!

**Comment by jayvdb** [comment]
Yup, see https://github.com/junaruga/rpm-py-installer/pull/177 for example and explanation.

**Comment by jayvdb** [comment]
And see https://build.opensuse.org/package/show/home:jayvdb:soe/python-pyops for the RPM package .spec I am building.

**Comment by d3vsf** [comment]
Hi @jayvdb ,
I created version v0.0.2 of pyops. Could you please check if the rpm build works properly?

Thank you!

**Comment by jayvdb** [comment]
I wasnt able to get `python setup.py test` working on Python 2.7, but `python tests/Test.py` worked except that it doesnt return an exit status if the tests fail.

Anyways, this problem is fixed.

However ... the Python 2 log looks like

```
[   86s] + /usr/bin/python2 ./tests/Test.py
[   86s] test_class_parameters (__main__.OpsTest) ... No handlers could be found for logger "pyops.core"
[   86s] ok
[   86s] test_fedeo_collection_search (__main__.OpsTest) ... FAIL
[   86s] test_fedeo_results_search (__main__.OpsTest) ... FAIL
[   86s] test_search_with_parameters (__main__.OpsTest) ... FAIL
[   86s] test_search_without_parameters (__main__.OpsTest) ... FAIL
[   86s] 
[   86s] ======================================================================
[   86s] FAIL: test_fedeo_collection_search (__main__.OpsTest)
[   86s] ----------------------------------------------------------------------
[   86s] Traceback (most recent call last):
[   86s]   File "./tests/Test.py", line 75, in test_fedeo_collection_search
[   86s]     self.assertTrue(len(raw_results) > 0)
[   86s] AssertionError: False is not true
[   86s] 
[   86s] ======================================================================
[   86s] FAIL: test_fedeo_results_search (__main__.OpsTest)
[   86s] ----------------------------------------------------------------------
[   86s] Traceback (most recent call last):
[   86s]   File "./tests/Test.py", line 83, in test_fedeo_results_search
[   86s]     self.assertTrue(len(raw_results) > 0)
[   86s] AssertionError: False is not true
[   86s] 
[   86s] ======================================================================
[   86s] FAIL: test_search_with_parameters (__main__.OpsTest)
[   86s] ----------------------------------------------------------------------
[   86s] Traceback (most recent call last):
[   86s]   File "./tests/Test.py", line 40, in test_search_with_parameters
[   86s]     self.assertTrue(len(raw_results) > 0)
[   86s] AssertionError: False is not true
[   86s] 
[   86s] ======================================================================
[   86s] FAIL: test_search_without_parameters (__main__.OpsTest)
[   86s] ----------------------------------------------------------------------
[   86s] Traceback (most recent call last):
[   86s]   File "./tests/Test.py", line 29, in test_search_without_parameters
[   86s]     self.assertTrue(len(raw_results) > 0)
[   86s] AssertionError: False is not true
[   86s] 
[   86s] ----------------------------------------------------------------------
[   86s] Ran 5 tests in 0.023s
[   86s] 
[   86s] FAILED (failures=4)
```

My guess is that those tests require the internet, and therefore they fail in an isolated VM without network used to build the rpms.

On Python 3.7, the errors are a bit more explicit about the cause, but also the exception handling needs to be improved.

```
[   88s] requests.exceptions.ConnectionError: HTTPSConnectionPool(host='catalog.terradue.com', port=443): Max retries exceeded with url: /sentinel1/search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe4a65e94e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[   88s] Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
[   88s] Traceback (most recent call last):
[   88s]   File "/home/abuild/rpmbuild/BUILD/pyops-0.0.2/pyops/core.py", line 119, in _get_search_template
[   88s]     r = requests.get(self.description_xml_url, headers={'Content-Type': 'application/atom+xml'})
[   88s]   File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
[   88s]     return request('get', url, params=params, **kwargs)
[   88s]   File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
[   88s]     return session.request(method=method, url=url, **kwargs)
[   88s]   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
[   88s]     prep = self.prepare_request(req)
[   88s]   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
[   88s]     hooks=merge_hooks(request.hooks, self.hooks),
[   88s]   File "/usr/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
[   88s]     self.prepare_url(url, params)
[   88s]   File "/usr/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
[   88s]     raise MissingSchema(error)
[   88s] requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
[   88s] expected string or bytes-like object
[   88s] Traceback (most recent call last):
[   88s]   File "/home/abuild/rpmbuild/BUILD/pyops-0.0.2/pyops/core.py", line 169, in _get_search_params
[   88s]     tags = re.findall('\{[\w\:\?]+\}', self.search_template_url)
[   88s]   File "/usr/lib64/python3.7/re.py", line 223, in findall
[   88s]     return _compile(pattern, flags).findall(string)
[   88s] TypeError: expected string or bytes-like object
[   88s] 'NoneType' object has no attribute 'startswith'
[   88s] Traceback (most recent call last):
[   88s]   File "/home/abuild/rpmbuild/BUILD/pyops-0.0.2/pyops/core.py", line 300, in search
[   88s]     if force_HTTPS and self.search_url.startswith('http://'):
[   88s] AttributeError: 'NoneType' object has no attribute 'startswith'
```

Some of your tests might be successful in an isolated VM if you store the OpenSearch *fetch* data in the repository and load it using file:// urls.  i.e. your tests dont need to verify that `requests` is working ... so you can skip that part.  A very cool tool for this is [`vcrpy`](https://pypi.org/project/vcrpy/).  And then add your test data files to the sdist (and check it using `check-manifest`).

**Comment by d3vsf** [comment]
> Some of your tests might be successful in an isolated VM if you store the OpenSearch fetch data in the repository and load it using file:// urls. ...

Yes, the tests need to access the internet or (at least) access to an OpenSearch server. I'm not sure I can include the fetched data... Anyhow I will check if it is possible!

Thank you so much!
